run:
  timeout: 3m
  build-tags:
    - dev

linters:
  enable:
    - funlen
    - gocyclo

linters-settings:
  funlen:
    lines: 120
    statements: 80
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15

issues:
  exclude-rules:
    - path: gen/
      linters:
        - funlen
        - gocyclo
  exclude-files:
    - _test\.go$
